Class {
	#name : 'TypeInferencer',
	#superclass : 'Object',
	#category : 'PBT-Property Specifcation',
	#package : 'PBT',
	#tag : 'Property Specifcation'
}

{ #category : 'as yet unclassified' }
TypeInferencer class >> inferExpectedResultType: method [

	"TODO: Implement me"
]

{ #category : 'as yet unclassified' }
TypeInferencer class >> inferTypeFrom: methods withName: variableName [

	"TODO: Implement me"

	
]

{ #category : 'private' }
TypeInferencer class >> typeOf: result [

	"Implement me"
]
